### PR TITLE
Make type of cell size subtype of AbstractFloat

### PR DESCRIPTION
**Pull request by OmriTreidel**
Type of dx is too restrictive

### CODE REVIEW

**Comment by JoshChristie** [comment]
Looks good. Not sure what's happening with failing on 0.6 and not liking list comprehensions.

**Comment by andyferris** [comment]
The error in question is:

> generated function body is not pure. this likely means it contains a closure or comprehension.

Oh dear. This is interesting. The definition of "pure" is that a function has no side effects: it takes an input and returns an output and doesn't modify _anything_. Like a mathematical function.

In Julia we have the _interesting_ situation that compiling things may have external consequences, such as creating new types. A closure is a kind of function-within-a-function that, as an internal Julia compiler implementation detail, creates a new Julia type that contains the captured variables. Thus, the side-effect is that calling the function generator creates a new type that _in theory_ is visible after the compilation is complete (in practice seeing this is almost impossible for end users, but to the compiler guys it is important that things aren't changing underneath them during certain stages of compilation). Also note that this is exactly the same as issue https://github.com/JuliaLang/julia/issues/16806 

(A comprehension also does something funky at the compiler level - they are specially blessed things and probably do something like the closure does for performance reasons).

All this is to say that this is a problem that will probably never go away - we should plan to change the relevant code at some point. Probably isn't too hard.

**Comment by c42f** [comment]
Uh, what?  I don't understand this PR.  Aren't the following exactly equivalent:

``` julia
foo(x::AbstractFloat) = x
bar{T<:AbstractFloat}(x::T) = x
```

I mean, with those definitions we have

``` julia
julia> foo(1.0)
1.0

julia> bar(1.0)
1.0

julia> foo(big(1.0))
1.000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> bar(big(1.0))
1.000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by JoshChristie** [comment]
Closing this. `spatial_grid.jl` was moved into [SpatialGrids.jl](https://github.com/FugroRoames/SpatialGrids.jl)

**Pull request closed without merging**
